### PR TITLE
Renovatebot

### PR DESCRIPTION
**Pull request by rpdelaney**
Add renovatebot config

### CODE REVIEW

**Comment by rpdelaney** [comment]
This is awesome @esacteksab , thank you. Does this run our shared validate action as well?

**Comment by esacteksab** [comment]
> This is awesome @esacteksab , thank you. Does this run our shared validate action as well?

I wasn't aware of a shared validate action. But I'll dig in and make it so.

**Comment by esacteksab** [comment]
> It's more of a nice to have than a requirement. I would approve this PR, but it's mine so I can't :D

Added. Thanks for the heads up. I'll be sure to add it on future repos.

**Review by ildeleaf — APPROVED** [review]
LGTM

**Pull request merged**
