### PR TITLE
Add name filtering and replace branch with arbitrary tag

### PR DESCRIPTION
**Pull request by cblkwell**
So, I have fixed up the amicleaner by improving some logging, allowing name filtering, and changing the --branch option to the more general --tag-key and --tag-value options.

This change successfully passes tests and mostly works in my real-world test environment, but I am running into an issue I'm not entirely sure about. This error seems to come up when I run the command line tool and get a large (>10) number of results:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x16582ac]

goroutine 1 [running]:
github.com/trussworks/truss-aws-tools/pkg/amiclean.(*AMIClean).PurgeImages(0xc000133ed0, 0xc000272180, 0xc, 0x10, 0x10, 0xffffffffffffffe2)
	/Users/cblkwell/go/src/github.com/trussworks/truss-aws-tools/pkg/amiclean/ami_cleaner.go:166 +0x2dc
main.cleanImages()
	/Users/cblkwell/go/src/github.com/trussworks/truss-aws-tools/cmd/ami-cleaner/main.go:67 +0x4f0
main.main()
	/Users/cblkwell/go/src/github.com/trussworks/truss-aws-tools/cmd/ami-cleaner/main.go:99 +0x1d8
exit status 2
```
I don't really understand why that line is causing problems, or what is going on here...I suspect this is me not doing a good job of memory hygiene.

One improvement I think may help is changing PurgeImages to a PurgeImage function that would operate on each image as it is found in the FindImagesToPurge function, but that is a fair bit of reengineering, so I wanted to checkpoint myself here and see if someone knows where I might be running into the weeds.

### CODE REVIEW

**Comment by cblkwell** [comment]
> I think what's happening is that for some images in the block that's erroring, the snapshotId value is nil. So, when you dereference it on line 165, the snapshotID var is set to "nil", and then on line 166, the reference for that address errors. Is there a reason you need to a pointer to the snapshot id instead of the value itself? You could either not use a pointer, or check if the snapshotID is not nil before appending it to `snapshotIds`

Hrm. I'm not sure how that would be possible...every AMI should have a snapshot associated with it (if it doesn't, that should get caught by the RootDeviceType check that that is encapsulated in. It's possible, but I don't know how you would have an AMI with an Ebs volume but no snapshot.

I'm using pointers because that's what Amazon uses for almost all of their values in things like Images, etc.

**Comment by amitch23** [comment]
I does seem odd to have an EBS volume without a snapshot. You could print out the value of `snapshotID` before appending it for a sanity check. You may want to check with someone else on this (@macrael would be a good resource), but if you're taking the memory address of snapshotID to append to snapshotIds, to then dereference it on line 188 (`SnapshotId: aws.String(*snapshot)`), it seems that you could just assign the string value instead of the pointer (assuming it's not nil)

**Comment by cblkwell** [comment]
Thanks to some help from @dynamike we figured out that it's trying to deregister an AMI that is just being shared with the account; I need to add another check to make sure the AMI is owned by our account.

**Comment by cblkwell** [comment]
I've fixed the issue that was causing the segfaults (trying to deregister AMIs we don't own). I am still thinking that changing PurgeImages to work on each AMI individually instead of in a batch might be a better architectural decision, but this now works the way I want for the most part.

**Pull request merged**
